<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>MauiBasics</RootNamespace>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationTitle>Việc nhỏ</ApplicationTitle>
    <ApplicationId>com.learning.viecnho</ApplicationId>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <SupportedOSPlatformVersion>24.0</SupportedOSPlatformVersion>
    <AndroidPackageFormats>apk</AndroidPackageFormats>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
  </PropertyGroup>
  <ItemGroup>
    <MauiIcon Include="Resources/AppIcon/appicon.svg" ForegroundFile="Resources/AppIcon/appiconfg.svg" Color="#115E59" />
    <MauiSplashScreen Include="Resources/AppIcon/appiconfg.svg" Color="#115E59" BaseSize="128,128" />
    <MauiImage Include="Resources/Images/*.svg" />
    <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.20" />
    <Compile Remove="tests/**/*.cs" />
    <EmbeddedResource Remove="tests/**/*" />
    <None Remove="tests/**/*" />
  </ItemGroup>
</Project>
